name: dart_http_client
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/HMasataka/dart_http_client

environment:
  sdk: ^3.4.3

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
